language: python
deploy:
  provider: heroku
  api_key:
    secure: BAjCatNIuX1V6aBHaGR0PfeJ4Y3izVLqvWziG2dMaXYh0bAKYanXqFfLmgkKi7Q6GVhCj7vXcfbqgWWNDS4UKyXu9YINBwvwfVsQwDKb1CufMgSvO6SwfXBf+YC+8bm+xeJv/gzbtTzIdVUAF5gI0jtM19+X1FiN5SP2q65+ZQLFPU+4UHXWuKsKn+lekuF0gh/9GKhOwXtSHbj2ZBxmSTY7tZsp79Gl49oagfVzGFba2LRDZSfoT7gTuBIxSlFkxZOjFlUvvicTAAB/VCR1MWVj3XYwxx+ZZTX3a84T84/CQchsNeJDgMWCkE/3+JLE6ojzDTNAajJ0O5fJkohvvjjBwSAv4jOjy/jiMnDWvad8UDCiFlR6zDqXrdefuj0kIo2EuF/rC243HUjj8wCqTIazg1bTkO4dhznRy0gBvv5l15VhqbLZwvkQk4Zm23L+Q+wX4ztVRYCO6njscwkYZtUdoY7em0bhjgM1Cfo02osnp0tVkVZPGBmqt7zsZK2CW+ffSUPw38m6GOqMRVsdqWRyG0Oc/86C59aCribS2iq/fahWQ+HpyTLCowJXFGzfF0QyP6fb9KDTUFc7NqKcvUZnIZ8yydUtiTtxrB6Ot7tVJZXT1mTFhwtOiUvHgbg7MPnme+Mp2qotPKqyQSXCWTmqny9NXjKkpFkgmSv42eM=
  run: rake db:migrate
