# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-11 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('complex_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_price', models.IntegerField()),
                ('price_per_unit', models.IntegerField()),
                ('squarefootage', models.IntegerField()),
                ('num_rooms', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='units',
            field=models.ManyToManyField(to='listings.Unit'),
        ),
    ]
