# Generated by Django 2.1.5 on 2019-03-22 17:04

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='images/')),
                ('neighborhood', multiselectfield.db.fields.MultiSelectField(choices=[('Jefferson Park Avenue', 'Jefferson Park Avenue'), ('Corner', 'Corner'), ('Rugby Road', 'Rugby Road'), ('West Main', 'West Main')], max_length=49, null=True)),
                ('approved', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('rating', models.IntegerField()),
                ('review_text', models.TextField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing.Building')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_rent', models.IntegerField()),
                ('square_footage', models.IntegerField()),
                ('num_bedrooms', models.IntegerField()),
                ('available', models.BooleanField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing.Building')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('building', models.CharField(max_length=100)),
                ('verified', models.BooleanField()),
            ],
        ),
    ]
