# Generated by Django 2.1.5 on 2019-04-14 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import housing.models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('pet_allowed', models.BooleanField()),
                ('is_furnished', models.BooleanField()),
                ('air_conditioning', models.BooleanField()),
                ('lease_length', models.IntegerField()),
                ('parking', models.BooleanField(null=True)),
                ('pool', models.BooleanField()),
                ('gym', models.BooleanField()),
                ('neighborhood', multiselectfield.db.fields.MultiSelectField(choices=[('Jefferson Park Avenue', 'Jefferson Park Avenue'), ('Corner', 'Corner'), ('Rugby Road', 'Rugby Road'), ('West Main', 'West Main')], max_length=49, null=True)),
                ('website_link', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('approved', models.BooleanField(blank=True, null=True)),
                ('admin', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('rating', models.IntegerField(validators=[housing.models.validate_review_rating])),
                ('helpful_score', models.IntegerField(default=0)),
                ('review_text', models.TextField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing.Building')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_rent', models.IntegerField()),
                ('square_footage', models.IntegerField()),
                ('num_bedrooms', models.IntegerField()),
                ('available', models.BooleanField()),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='housing.Building')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing.Review')),
            ],
        ),
    ]
