# Generated by Django 2.1.5 on 2019-04-14 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='header',
            field=models.CharField(default='epic', max_length=100),
            preserve_default=False,
        ),
    ]
