# Generated by Django 2.1.5 on 2019-04-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='helpful_score',
            field=models.IntegerField(default=0),
        ),
    ]
