# Generated by Django 2.1.5 on 2019-04-15 05:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('housing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='favorites',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
