# Generated by Django 2.1.5 on 2019-04-29 03:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0002_auto_20190429_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='monthly_rent',
            field=models.IntegerField(verbose_name=django.core.validators.MinValueValidator(1)),
        ),
        migrations.AlterField(
            model_name='unit',
            name='num_bathrooms',
            field=models.IntegerField(verbose_name=django.core.validators.MinValueValidator(1)),
        ),
        migrations.AlterField(
            model_name='unit',
            name='num_bedrooms',
            field=models.IntegerField(verbose_name=django.core.validators.MinValueValidator(1)),
        ),
        migrations.AlterField(
            model_name='unit',
            name='square_footage',
            field=models.IntegerField(verbose_name=django.core.validators.MinValueValidator(1)),
        ),
    ]
