# Generated by Django 2.1 on 2019-02-27 01:07

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0002_unit_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='neighborhood',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Jefferson Park Avenue'), (2, 'Corner'), (3, 'Rugby Road'), (4, 'West Main')], max_length=7, null=True),
        ),
    ]
