# Generated by Django 2.1 on 2019-03-03 21:04

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0003_building_neighborhood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='neighborhood',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Jefferson Park Avenue', 'Jefferson Park Avenue'), ('Corner', 'Corner'), ('Rugby Road', 'Rugby Road'), ('West Main', 'West Main')], max_length=49, null=True),
        ),
    ]
