# Generated by Django 2.1.5 on 2019-03-04 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0004_auto_20190303_2104'),
        ('housing', '0003_review_date'),
    ]

    operations = [
    ]
