# Generated by Django 2.1.5 on 2019-04-29 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0004_auto_20190429_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='monthly_rent',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='unit',
            name='num_bathrooms',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='unit',
            name='num_bedrooms',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='unit',
            name='square_footage',
            field=models.IntegerField(),
        ),
    ]
